### ISSUE TITLE
Missing build files

### ISSUE THREAD

**Issue by Hedydd** [ChromisPos/ChromisPOS#1] opened 2015-09-03 09:40 UTC
I have just cloned the repository and tried to open the project in NetBeans - The build files seem to be missing.

Also please clarify the baseline for this source - is it 3.81 with johnl modifications?

Thanks

http://docs.oracle.com/cd/E50453_01/doc.80/e50452/create_japps.htm#NBDAG2974

**Comment by cubanflyer** [comment] 2015-09-03 10:06
Hi

This is not a mavenized project, so you need to set it up correctly in 
netbeans. Just ran through the steps and it is all working using the 
downloaded code.

The baseline is for 3.81 with johnl 1.6 mods.

John

On 03/09/2015 10:40, Hedydd wrote:
>
> I have just cloned the repository and tried to open the project in 
> NetBeans - The build files seem to be missing.
>
> Also please clarify the baseline for this source - is it 3.81 with 
> johnl modifications?
>
> Thanks
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1>.Web Bug from 
> https://github.com/notifications/beacon/AA4-1wkS-9nM0exgJEHkGO7yVkksrbeJks5ouA0XgaJpZM4F3G_B.gif
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hedydd** [comment] 2015-09-03 11:37
Hi John – I can see the project.xml file in the source root directory but netbeans project open does not recognise it as a project directory – I have gone back to a clean install of the unicentapos 3.81 source and have the same issue – I previously opened this OK so it must be a problem with my NetBeans installation (or Windows 10 upgrade which was done recently), I have googled a few similar issues but not found an answer yet – I will continue to investigate and let you know how I get on.

 

John

**Comment by Hedydd** [comment] 2015-09-03 11:50
OK – just found the developer guide and remember doing that last time too – sorry to bother you – you are welcome to put RTFM in my github issue report J

 

John

**Comment by cubanflyer** [comment] 2015-09-03 12:06
Hi John

I want to mavenize the project when i get the chance, I have only be 
playing with java for about 2 years part time, so I am still getting my 
head around it. I used to use assemble Z80 & x86 but that was along time 
ago.

I will write a manual for chromis as soon I get some time, trying to get 
the first release out seems to have teamk for ever.

John



On 03/09/2015 12:50, John Barrett wrote:
> OK – just found the developer guide and remember doing that last time 
> too – sorry to bother you – you are welcome to put RTFM in my github 
> issue report J
>
>
>
> John
>
>
>
>
>
> From: John Lewis [mailto:notifications@github.com]
> Sent: 03 September 2015 11:06
> To: ChromisPos/ChromisPOS
> Cc: John Barrett
> Subject: Re: [ChromisPOS] Missing build files (#1)
>
>
>
> Hi
>
> This is not a mavenized project, so you need to set it up correctly in
> netbeans. Just ran through the steps and it is all working using the
> downloaded code.
>
> The baseline is for 3.81 with johnl 1.6 mods.
>
> John
>
> On 03/09/2015 10:40, Hedydd wrote:
> >
> > I have just cloned the repository and tried to open the project in
> > NetBeans - The build files seem to be missing.
> >
> > Also please clarify the baseline for this source - is it 3.81 with
> > johnl modifications?
> >
> > Thanks
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/ChromisPos/ChromisPOS/issues/1>.Web Bug from
> > 
> https://github.com/notifications/beacon/AA4-1wkS-9nM0exgJEHkGO7yVkksrbeJks5ouA0XgaJpZM4F3G_B.gif
> >
>
>
>
> ---
> This email has been checked for viruses by Avast antivirus software.
> https://www.avast.com/antivirus
>
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137398349> 
> . 
> <https://github.com/notifications/beacon/AKeQDqacDeCnImJCeACUeB3uOIucVf46ks5ouBMSgaJpZM4F3G_B.gif> 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137415452>.Web 
> Bug from 
> https://github.com/notifications/beacon/AA4-112pQDGahGVxhDMNx41rGFBpDc-tks5ouCuSgaJpZM4F3G_B.gif
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hedydd** [comment] 2015-09-03 12:25
Jack has mavenised 3.91.1 and it does build very easily – you may find it less work at this early stage to take 3.91.1 as your base line, I would imagine it easier for you to put your changes into 3.91.1 rather than mavenising later which will involve major directory structure changes.

 

I have been developing software since 1980 in most major languages. I have not decided definitely which source base to use yet, yours or Jack’s, but whichever one I use will get:

 

                Android app to enter stock deliveries – including muti-pack products (i.e. scanning a barcode on a box of 48 mars bars will add 48 to the quantity of individual mars bars in stock)

                Android app to do stock checks (including barcode scanning)

                New reports

                Integration with Quickbooks 2015 using the QuickBooks API for sales and stock updates into Quickbooks.

 

At the moment Jack does not appear interested in working with anyone else – this is a major issue for me as I want to be able to take future product enhancements and bug fixes.

 

John

**Comment by cubanflyer** [comment] 2015-09-03 13:01
Hi John

It sounds like you have some of the same ideas as I do. I work in an 
area where retail forms a big revenue stream and I was responsible for 
the retail area in the cinema I was manager at, before moving to IT.

I think the issue for me with the maven idea is just understanding the 
setting up of it, I also have a couple of Libraries that have been 
customized one is liquibase, (it has a blob size limit by deault), and 
convert which does the work to change alot in the background. I know it 
sounds evil, but convert makes it difficult to return to Unicenta with 
the same database.


John

On 03/09/2015 13:25, John Barrett wrote:
> Jack has mavenised 3.91.1 and it does build very easily – you may find 
> it less work at this early stage to take 3.91.1 as your base line, I 
> would imagine it easier for you to put your changes into 3.91.1 rather 
> than mavenising later which will involve major directory structure 
> changes.
>
>
>
> I have been developing software since 1980 in most major languages. I 
> have not decided definitely which source base to use yet, yours or 
> Jack’s, but whichever one I use will get:
>
>
> Android app to enter stock deliveries – including muti-pack products 
> (i.e. scanning a barcode on a box of 48 mars bars will add 48 to the 
> quantity of individual mars bars in stock)
>
> Android app to do stock checks (including barcode scanning)
>
> New reports
>
> Integration with Quickbooks 2015 using the QuickBooks API for sales 
> and stock updates into Quickbooks.
>
>
> At the moment Jack does not appear interested in working with anyone 
> else – this is a major issue for me as I want to be able to take 
> future product enhancements and bug fixes.
>
>
>
> John
>
>
>
>
>
> From: John Lewis [mailto:notifications@github.com]
> Sent: 03 September 2015 13:07
> To: ChromisPos/ChromisPOS
> Cc: John Barrett
> Subject: Re: [ChromisPOS] Missing build files (#1)
>
>
>
> Hi John
>
> I want to mavenize the project when i get the chance, I have only be
> playing with java for about 2 years part time, so I am still getting my
> head around it. I used to use assemble Z80 & x86 but that was along time
> ago.
>
> I will write a manual for chromis as soon I get some time, trying to get
> the first release out seems to have teamk for ever.
>
> John
>
>
>
> On 03/09/2015 12:50, John Barrett wrote:
> > OK – just found the developer guide and remember doing that last time
> > too – sorry to bother you – you are welcome to put RTFM in my github
> > issue report J
> >
> >
> >
> > John
> >
> >
> >
> >
> >
> > From: John Lewis [mailto:notifications@github.com]
> > Sent: 03 September 2015 11:06
> > To: ChromisPos/ChromisPOS
> > Cc: John Barrett
> > Subject: Re: [ChromisPOS] Missing build files (#1)
> >
> >
> >
> > Hi
> >
> > This is not a mavenized project, so you need to set it up correctly in
> > netbeans. Just ran through the steps and it is all working using the
> > downloaded code.
> >
> > The baseline is for 3.81 with johnl 1.6 mods.
> >
> > John
> >
> > On 03/09/2015 10:40, Hedydd wrote:
> > >
> > > I have just cloned the repository and tried to open the project in
> > > NetBeans - The build files seem to be missing.
> > >
> > > Also please clarify the baseline for this source - is it 3.81 with
> > > johnl modifications?
> > >
> > > Thanks
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/ChromisPos/ChromisPOS/issues/1>.Web Bug from
> > >
> > 
> https://github.com/notifications/beacon/AA4-1wkS-9nM0exgJEHkGO7yVkksrbeJks5ouA0XgaJpZM4F3G_B.gif
> > >
> >
> >
> >
> > ---
> > This email has been checked for viruses by Avast antivirus software.
> > https://www.avast.com/antivirus
> >
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137398349> 
>
> > .
> > 
> <https://github.com/notifications/beacon/AKeQDqacDeCnImJCeACUeB3uOIucVf46ks5ouBMSgaJpZM4F3G_B.gif> 
>
> >
> >
> > —
> > Reply to this email directly or view it on GitHub
> > 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137415452>.Web 
>
> > Bug from
> > 
> https://github.com/notifications/beacon/AA4-112pQDGahGVxhDMNx41rGFBpDc-tks5ouCuSgaJpZM4F3G_B.gif
> >
>
>
>
> ---
> This email has been checked for viruses by Avast antivirus software.
> https://www.avast.com/antivirus
>
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137418104> 
> . 
> <https://github.com/notifications/beacon/AKeQDhDi42y3Txs9yPxkt3gY_8j2kH7Vks5ouC9OgaJpZM4F3G_B.gif> 
>
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137420876>.Web 
> Bug from 
> https://github.com/notifications/beacon/AA4-11-R-S8qWZDioogRVzZ_kLnPI9qpks5ouDOggaJpZM4F3G_B.gif
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hedydd** [comment] 2015-09-03 14:00
I have just had a quick look into the index too long error. It is due to (in createdb.xml)
            <column name="ID" type="varchar(255)">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="PRODUCT" type="varchar(255)">
                <constraints primaryKey="true" nullable="false"/>
            </column>
            <column name="PRODUCT2" type="varchar(255)">
                <constraints primaryKey="true" nullable="false"/>
            </column>
So ID, PRODUCT and PRODUCT2 are all defined as 255 characters - each character can be up to 4 bytes depending on the character set in use hence the problem (255 + 255 + 255) x 4 = LOTS

It is VERY inefficient to have 255 character IDs in a database - these could be reduced in size here and through-out the database.

**Comment by cubanflyer** [comment] 2015-09-03 14:10
Hi John

Thanks for that.

I copied these setting from the Unicenta code. I was just in the process 
of installing MySql 5.1.66, as I am running 5.6, to see if I got the 
same error.

Regards
John

On 03/09/2015 15:00, John Barrett wrote:
>
> I have just had a quick look into the index too long error. It is due 
> to (in createdb.xml)
>
>
>
>
>
>
>
>
>
> So ID, PRODUCT and PRODUCT2 are all defined as 255 characters - each 
> character can be up to 4 bytes depending on the character set in use 
> hence the problem (255 + 255 + 255) x 4 = LOTS
>
> It is VERY inefficient to have 255 character IDs in a database - these 
> could be reduced in size here and through-out the database.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137458967>.Web 
> Bug from 
> https://github.com/notifications/beacon/AA4-17XqDNaD7gU-9POmyptsBY7dHyiBks5ouEoOgaJpZM4F3G_B.gif
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hedydd** [comment] 2015-09-03 14:20
I thinkthe problem is that you are not specifying UTF-8 as the default character set in the create table statements in SQL this would be:
 CREATE TABLE ........      DEFAULT CHARACTER SET utf8

I do not know enough about Liquibase but suspect that is not being specified when it creates the tables.

utf8 is an 8 bit character set which removes the issue (although leaves the inneficiency of 255 character IDs)

**Comment by cubanflyer** [comment] 2015-09-03 14:35
I will have a look at it, I have run the install against Mysql 5.1.66 
and it installed. I hav etried changing the collation on the DB as it is 
created from latin-1 to UTF8 and still unable to reproduce the error, 
puzzling !

I am still new with Liquibase, but it just made more sense than all the 
scripts that were in the code.

John

On 03/09/2015 15:20, John Barrett wrote:
>
> I thinkthe problem is that you are not specifying UTF-8 as the default 
> character set in the create table statements in SQL this would be:
> CREATE TABLE ........ DEFAULT CHARACTER SET utf8
>
> I do not know enough about Liquibase but suspect that is not being 
> specified when it creates the tables.
>
> utf8 is an 8 bit character set which removes the issue (although 
> leaves the inneficiency of 255 character IDs)
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137464201>.Web 
> Bug from 
> https://github.com/notifications/beacon/AA4-1-U04QPq6tw4_3LOQxLrtUjKd-N3ks5ouE7DgaJpZM4F3G_B.gif
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hedydd** [comment] 2015-09-04 15:05
Hi John - I managed to spend some time investigating today by comparing a unipos and a chromis database - the difference is use of the innodb engine is specified in the unipos CREATE TABLE - chromis does not specify so mySQL uses the default which in my case is myISAM.

You need to specify "engine innodb" in the create table statements. I found the link below which seems to show how to do it in liquibase but it is not straight forward because you sometimes have create tables with create constraints and insert data statements in one changeset. These may need to be broken into multiple changesets.

http://www.liquibase.org/documentation/modify_sql.html

Doing this change is a short term fix - the problem highlights a greater issue of >255 character primary keys which also exists in unipos which should be fixed in the longer term for efficiency.

**Comment by cubanflyer** [comment] 2015-09-04 19:06
Hi John

Thanks for that, I will look at the entire set of Liquibase scripts and 
modify any create tables. When it is done can I send you a copy to test?

John



On 04/09/2015 16:05, John Barrett wrote:
>
> Hi John - I managed to spend some time investigating today by 
> comparing a unipos and a chromis database - the difference is use of 
> the innodb engine is specified in the unipos CREATE TABLE - chromis 
> does not specify so mySQL uses the default which in my case is myISAM.
>
> You need to specify "engine innodb" in the create table statements. I 
> found the link below which seems to show how to do it in liquibase but 
> it is not straight forward because you sometimes have create tables 
> with create constraints and insert data statements in one changeset. 
> These may need to be broken into multiple changesets.
>
> http://www.liquibase.org/documentation/modify_sql.html
>
> Doing this change is a short term fix - the problem highlights a 
> greater issue of >255 character primary keys which also exists in 
> unipos which should be fixed in the longer term for efficiency.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137761036>.Web 
> Bug from 
> https://github.com/notifications/beacon/AA4-193lQQtKsFFOB9kFjsrOCojpt0fZks5ouaq3gaJpZM4F3G_B.gif
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by cubanflyer** [comment] 2015-09-04 20:21
Hi John

I have been playing with the Liquibase scripts and it appears to create 
the tables in the correct format on both versions of MySql I am using 
here. I have found that you can not use the liquibase command you found 
if you are doing anything else in the same changeset as creating the 
table. I have created a changeset that changes to InnoDB if required.


Regards
John

On 04/09/2015 16:05, John Barrett wrote:
>
> Hi John - I managed to spend some time investigating today by 
> comparing a unipos and a chromis database - the difference is use of 
> the innodb engine is specified in the unipos CREATE TABLE - chromis 
> does not specify so mySQL uses the default which in my case is myISAM.
>
> You need to specify "engine innodb" in the create table statements. I 
> found the link below which seems to show how to do it in liquibase but 
> it is not straight forward because you sometimes have create tables 
> with create constraints and insert data statements in one changeset. 
> These may need to be broken into multiple changesets.
>
> http://www.liquibase.org/documentation/modify_sql.html
>
> Doing this change is a short term fix - the problem highlights a 
> greater issue of >255 character primary keys which also exists in 
> unipos which should be fixed in the longer term for efficiency.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/ChromisPos/ChromisPOS/issues/1#issuecomment-137761036>.Web 
> Bug from 
> https://github.com/notifications/beacon/AA4-193lQQtKsFFOB9kFjsrOCojpt0fZks5ouaq3gaJpZM4F3G_B.gif
>



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hedydd** [comment] 2015-09-06 11:29
The default DB engine is specific to the MySQL installation not just the version, the MySQL server I am running comes inbuilt in a QNAP NAS box so QNAP must have set MyISAM as the default engine to use. According to the article below, the default out of the box has changed on the later versions of MySQL but that would not prevent a system administrator from changing that default.

 

You may find this useful:

https://dev.mysql.com/doc/refman/5.5/en/innodb-default-se.html

 

You could try applying this after the table is created:

                ALTER TABLE {tablename} ENGINE = InnoDb;

**Comment by Hedydd** [comment] 2015-09-06 11:31
Scrub that below – ALTER table after CREATE would not work because it is the CREATE that is failing at the moment. You either need to set the default engine on the database before the CREATE statements or set the engine in each CREATE.

 

John

 

 

From: John Barrett [mailto:me@john-barrett.uk] 
Sent: 06 September 2015 12:29
To: 'ChromisPos/ChromisPOS'
Subject: RE: [ChromisPOS] Missing build files (#1)

 

The default DB engine is specific to the MySQL installation not just the version, the MySQL server I am running comes inbuilt in a QNAP NAS box so QNAP must have set MyISAM as the default engine to use. According to the article below, the default out of the box has changed on the later versions of MySQL but that would not prevent a system administrator from changing that default.

 

You may find this useful:

https://dev.mysql.com/doc/refman/5.5/en/innodb-default-se.html

 

You could try applying this after the table is created:

                ALTER TABLE {tablename} ENGINE = InnoDb;

**Closed** 2015-09-08 08:41 UTC

**Comment by Hedydd** [comment] 2015-09-08 08:54
Issue closed as the original problem is resolved and a new issue raised for the large primary key problem

**Comment by cubanflyer** [comment] 2015-09-12 15:50
Hi John

I am still finding my way around github, I have only ever used it for a 
safe file storage area. The question do you know how I do a merge?

Any help would be great.

John



---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by Hedydd** [comment] 2015-09-13 05:46
Hi John,

A good place to start on GitHub is here : https://guides.github.com/activities/hello-world/

 

The usual way of working is that the master branch is your bleeding edge and contains the future releases. When you are ready to release you create a branch from the master and create your release notes, executable files etc on the branch. These can then go into Beta testing. You have the option of re-releasing the branch by pulling bug fixes into the release branch from other branches. You could also fix bugs on the release branch and then pull those changes back into the master.

 

The first thing you should do is look at the pull request I have created, this allows you to take my changes into the main product, you need to selectively apply the changes you want into your master branch (github uses the term ‘cherry pick’). You are just taking bug fixes at this stage, I have tried to commit bugfixes separately from enhancements on my fork to make this job easier. Once you are happy with what you have on your master, create a branch from it, create the release files etc on this branch and release a beta from the branch.

 

Once you have the branch for the release, you can then take the rest of my changes and merge these back into your ‘master’ ready for the next release.

 

If you add me as a developer on the main project source files, I can modify files directly in the project rather than working on my own fork all the time. What would then happen is I would create a branch, do my product enhancements on that branch, and then merge my branch back to master once they were completed. I could still fork to my own repository if I wanted to work on something privately.

 

John
